name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  slack-webhook-url: 
    required: true
    description: 'webhook url for slack. Please add as a secret or Slack will revoke it.'
  slack-channel:
    required: true
    description: 'the slack channel to send the mesage to'
  team-members:
    required: true
    description: 'a comma delimited list of team members'
  prepend-message: 
    required: false
    description: 'The message preceding the randomized list'
    default: "Today's standup order is:"
  icon-emoji:
    required: false
    description: 'The slack emoji to use for the message'
    default: ':game_die:'
  bot-username:
    required: false
    description: "The bot's username in slack"
    default: 'Standup Order Bot'
  include-user-emojis:
    required: false
    description: "Include the user's handle emoji (:handle:) in the list"
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
