name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          slack-channel: luketomlinson-chatops
          team-members: 'luketomlinson,test,game_die,another,foo,bar,baz,sleepy,happy,dopey,grumpy'
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
