name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          slack-channel: luketomlinson-chatops
          team-members: 'luketomlinson,test-gif,game_die,thank-you2,food,barney,bazinga,sleepy,joy,developers,grumpycat'
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
